spring.application.name = ${DATABASE_NAME}
spring.datasource.url = ${DATABASE_URL}
spring.datasource.username = ${DATABASE_USERNAME}
spring.datasource.password = ${DATABASE_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=QuizAppPool

spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

openapi.api.url = ${OPENAI_URL}
openapi.api.model = ${OPENAI_MODEL}
openapi.api.key = ${OPENAI_KEY}

aws.s3.acces.key = ${AWS_ACCESS_KEY}
aws.s3.secret.key = ${AWS_SECRET_KEY}
aws.s3.bucket.name = ${AWS_BUCKET_NAME}

spring.security.user.name = ${APP_USERNAME}
spring.security.user.password = ${APP_PASSWORD}